from src.llm.llm_api import create_openai_client
import subprocess
import os
import re
import json
from collections import defaultdict
import difflib
from openai import InternalServerError, APITimeoutError, APIError
# from error_analysis import run_opt_verify, collect_source_errors
import tempfile
import editdistance
import shutil

_MAIN_PATTERN = re.compile(r'int\s+main\s*\([^)]*\)\s*{', re.MULTILINE)
def extract_main_body(text: str) -> str:
    """
    : C （ \\n ，）
    : main （），
    """
    code = text

    if "\\n" in code and "\n" not in code:
        code = code.replace("\\n", "\n")

    m = _MAIN_PATTERN.search(code)
    if not m:
        return ""

    start_brace = code.find("{", m.start())
    if start_brace == -1:
        return ""

    depth = 0
    end_brace = None
    for i, ch in enumerate(code[start_brace:], start_brace):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                end_brace = i
                break

    if end_brace is None:
        return ""

    body = code[start_brace + 1:end_brace]
    return body.strip()


# ---------------------------
# ---------------------------
def snapshot_ll_before_retry(ll_path: str, retry_idx: int) -> str:
    """
     retry ， ll_path  retry_{retry_idx}/ ，
    ，。
    """
    base_dir = os.path.dirname(ll_path)
    base_name = os.path.basename(ll_path)

    retry_dir = os.path.join(base_dir, f"retry_{retry_idx}")
    os.makedirs(retry_dir, exist_ok=True)

    new_ll_path = os.path.join(retry_dir, base_name)

    shutil.copy2(ll_path, new_ll_path)

    return new_ll_path



# Function to calculate edit similarity
def normalize_spaces(s):
    if not s:
        s = ''
    s = re.sub(r'([.,!?();+\-/*{}^&=!])', r' \1 ', s)  # comment removed
    s = ' '.join(s.split())
    return s

def normalize_variables(s):
    s = re.sub(r'%[\w\.\-]+', '%VAR', s)
    return s

def preprocess(s):
    s = normalize_spaces(s)
    s = normalize_variables(s)
    return s

def get_normalized_edit_similarity(ground_truth, pred):
    if not pred:
        return 0.0, False

    gt = preprocess(ground_truth)
    out = preprocess(pred)

    exact_match = (gt == out)
    ed = editdistance.distance(gt, out)
    normalized = ed / max(len(gt), len(out))
    return 1 - normalized

def fix_with_llm_api(source_code, error_message, error_message1, client, input_asm_prompt, model_name: str = "deepseek-chat", timeout: int = 300):
    prompt = f"""# Below is LLVM IR function generated by translating x86_64 assembly with no optimization (O0). However, the generated IR contains some errors that need to be fixed.
-Please preserve the SSA (Static Single Assignment) structure and ensure the IR is functionally correct.
-Please output ONLY the corrected LLVM IR code.Do not include any explanations, comments, or annotations.
#LLVM IR:'''llvm
{source_code}
'''
#error_message :
{error_message}
#Original assembly:
'''asm
{input_asm_prompt}
'''
"""

    print(prompt)
    try:
        stream = client.chat.completions.create(
            model=model_name,
            messages=[{"role": "system", "content": "You are a compiler expert who is good at disassembly."},
            {"role": "user", "content": prompt}
            ],
            stream=False,
            timeout=timeout
        )

    except InternalServerError as e:
        print(f"[LLM] InternalServerError (likely 502). retry once after 3s. err={e}")
        return "__SERVER_ERROR__"
    except APITimeoutError:
        print("⚠️ LLM  300 ，，")
        return "__TIMEOUT__"  # comment removed
    except APIError as e:
        print(f"⚠️ LLM API : {e}")
        return "__Failed__"

    source_code = stream.choices[0].message.content
    code_pattern = re.compile(r"```ir\n(.*?)\n```", re.DOTALL)
    match = code_pattern.search(source_code)
    code_pattern1 = re.compile(r"```llvm\n(.*?)\n```", re.DOTALL)
    match1 = code_pattern1.search(source_code)
    if match:
        return match.group(1).strip()
    elif match1:
        return match1.group(1).strip()
    else:
        return source_code



def fix_with_llm_api_testcases(source_code, error_message, error_message1, client, input_asm_prompt, test_cases, model_name: str = "deepseek-chat", timeout: int = 300):
    prompt = f"""# Below is LLVM IR function generated by translating x86_64 assembly. However, the generated IR contains some semantic errors that need to be fixed.
-The function's functionality is different from the original Assembly, that is, it failed the given test case. Please ensure that IR can pass all the given test cases.
-Ensure that the syntax of IR is correct and no compilation errors occur.
-Output ONLY the corrected LLVM IR code.Do not include any explanations, comments, or annotations.
#LLVM IR:'''llvm
{source_code}
'''
#error_message :
{error_message}
#Test cases:
{test_cases}
"""

    print(prompt)
    try:
        stream = client.chat.completions.create(
            model=model_name,
            messages=[{"role": "system", "content": "You are a compiler expert who is good at disassembly."},
            {"role": "user", "content": prompt}
            ],
            stream=False,
            timeout=timeout
        )
    except InternalServerError as e:
        print(f"[LLM] InternalServerError (likely 502). retry once after 3s. err={e}")
        return "__SERVER_ERROR__"
    except APITimeoutError:
        print("⚠️ LLM  300 ，，")
        return "__TIMEOUT__"  # comment removed
    except APIError as e:
        print(f"⚠️ LLM API : {e}")
        return "__Failed__"
    source_code = stream.choices[0].message.content
    code_pattern = re.compile(r"```ir\n(.*?)\n```", re.DOTALL)
    match = code_pattern.search(source_code)
    code_pattern1 = re.compile(r"```llvm\n(.*?)\n```", re.DOTALL)
    match1 = code_pattern1.search(source_code)
    if match:
        return match.group(1).strip()
    elif match1:
        return match1.group(1).strip()
    else:
        return source_code



def fix_with_llm_api_phi(source_code, error_message, error_message1, client, input_asm_prompt, model_name: str = "deepseek-chat", timeout: int = 300):
    prompt = f"""# Below is LLVM IR function generated by translating x86_64 assembly with no optimization (O0). However, errors occurred when using the PHI command.
#LLVM IR:'''llvm
{source_code}
'''
#error_message :
{error_message}
Please follow the rules of the phi directive to correct the errors. Output ONLY the corrected LLVM IR code.Do not include any explanations, comments, or annotations:
LLVM IR Phi Instruction Rules (Concise):
1. Position: Must be the first instructions in a basic block.
2. Syntax: `%result = phi <type> [ %value1, %bb1 ], [ %value2, %bb2 ], ...`
3. Pairs: Each predecessor basic block must have a corresponding `[ value, label ]` pair.
4. Type: All values in the list must be of the same type.
5. Predecessors: The labels must be immediate predecessors of the current block. The number and order of pairs must account for all possible incoming control flow edges to the block.
#Original assembly:
'''asm
{input_asm_prompt}
'''
"""

    print(prompt)
    try:
        stream = client.chat.completions.create(
            model=model_name,
            messages=[{"role": "system", "content": "You are a compiler expert who is good at disassembly."},
            {"role": "user", "content": prompt}
            ],
            stream=False,
            timeout=timeout
        )

    except InternalServerError as e:
        print(f"[LLM] InternalServerError (likely 502). retry once after 3s. err={e}")
        return "__SERVER_ERROR__"
    except APITimeoutError:
        print("⚠️ LLM  300 ，，")
        return "__TIMEOUT__"  # comment removed
    except APIError as e:
        print(f"⚠️ LLM API : {e}")
        return "__Failed__"

    source_code = stream.choices[0].message.content
    code_pattern = re.compile(r"```ir\n(.*?)\n```", re.DOTALL)
    match = code_pattern.search(source_code)
    code_pattern1 = re.compile(r"```llvm\n(.*?)\n```", re.DOTALL)
    match1 = code_pattern1.search(source_code)
    if match:
        return match.group(1).strip()
    elif match1:
        return match1.group(1).strip()
    else:
        return source_code


def try_run_ll_file(filename, ir_test=None, ir_func=None, temp_dir: str = "/tmp"):
    os.makedirs(temp_dir, exist_ok=True)
    #print(filename)
    ll_object_file = filename.replace('.ll', '.o')
    compile_success = False
    exec_success = False
    similarity = -1.0

    if ir_func:
        with open(filename, 'r') as f:
            gen_code = f.read()
        similarity = get_normalized_edit_similarity(ir_func, gen_code)
    try:
        result_compile = subprocess.run(
            ['clang', '-c', filename, '-o', ll_object_file, '-lm', '-lc'],
            capture_output=True, text=True, timeout=15
        )

        if result_compile.returncode != 0:
            #print(result_compile.stderr)
            return False, False, result_compile.stderr, similarity
        compile_success = True
        
        if ir_test:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".c", dir=temp_dir) as c_temp_file:
                c_temp_file_path = c_temp_file.name
                c_temp_file.write(ir_test.encode())

            c_object_file = c_temp_file_path.replace('.c', '.o')
            result_c = subprocess.run(
                ['clang', '-c', c_temp_file_path, '-o', c_object_file, '-lm', '-lc'],
                capture_output=True, text=True, timeout=15
            )

            if result_c.returncode != 0:
                #print(result_c.stderr)
                if os.path.exists(ll_object_file): os.remove(ll_object_file)
                if os.path.exists(c_temp_file_path): os.remove(c_temp_file_path)
                return True, False, result_c.stderr, similarity

            output_binary = filename.replace('.ll', '_exe')
            result_link = subprocess.run(
                ['clang', ll_object_file, c_object_file, '-lm', '-lc', '-o', output_binary],
                capture_output=True, text=True, timeout=15
            )

            if result_link.returncode != 0:
                #print(result_link.stderr)
                if os.path.exists(c_temp_file_path): os.remove(c_temp_file_path)
                if os.path.exists(c_object_file): os.remove(c_object_file)
                if os.path.exists(ll_object_file): os.remove(ll_object_file)
                return True, False, result_link.stderr, similarity

            result_exec = subprocess.run(
                [output_binary],
                capture_output=True, text=True, timeout=15
            )

            if result_exec.returncode != 0:
                #print(result_exec.stderr)
                if os.path.exists(output_binary): os.remove(output_binary)
                if os.path.exists(c_temp_file_path): os.remove(c_temp_file_path)
                if os.path.exists(c_object_file): os.remove(c_object_file)
                if os.path.exists(ll_object_file): os.remove(ll_object_file)
                return True, False, result_exec.stderr, similarity

            exec_success = True
            if os.path.exists(output_binary): os.remove(output_binary)
            if os.path.exists(c_temp_file_path): os.remove(c_temp_file_path)
            if os.path.exists(c_object_file): os.remove(c_object_file)
            if os.path.exists(c_object_file): os.remove(c_object_file)

        #else:
            #success = True

        #if ir_func:
            #with open(filename, 'r') as f:
                #gen_code = f.read()
                #similarity = get_normalized_edit_similarity(ir_func, gen_code)

    except subprocess.TimeoutExpired:
        return False, False, "TimeoutExpired", similarity
    finally:
        if os.path.exists(ll_object_file):
            os.remove(ll_object_file)

    return compile_success, exec_success, "", similarity


def run_refinement(
    json_path: str,
    input_ll_dir: str,
    output_ll_dir: str,
    file_pattern: str = "onlyfunc_{task_id}_{opt}.o.ll",
    retry_limit: int = 5,
    api_key: str | None = None,
    base_url: str = "https://api.deepseek.com",
    llm_model_name: str = "deepseek-chat",
    llm_timeout: int = 300,
    temp_dir: str = "/tmp",
):
    with open(json_path, 'r') as f:
        testsets = json.load(f)

    os.makedirs(output_ll_dir, exist_ok=True)
    os.makedirs(temp_dir, exist_ok=True)

    edit_sim_dict = defaultdict(list)
    edit_sim_all = []
    success_counter_compile = defaultdict(int)
    success_counter_exec = defaultdict(int)

    client = create_openai_client(api_key=api_key or os.environ.get("DEEPSEEK_API_KEY", ""), base_url=base_url)

    for testset in testsets:
        task_id = testset["task_id"]
        opt = testset["type"]
        ir_test = testset["ir_test"]
        input_asm = testset["input_asm_prompt"]
        ir_func = testset["ir_func"]

        candidate_path = testset.get("output_ll_path")
        if candidate_path:
            filename = candidate_path
        else:
            filename = os.path.join(input_ll_dir, file_pattern.format(task_id=task_id, opt=opt))

        print(filename)
        if not os.path.exists(filename):
            print(f"File not found: {filename}")
            continue

        compile_success, exec_success, error_msg_compile, similarity = try_run_ll_file(filename, ir_test, ir_func, temp_dir=temp_dir)

        retry_count = 1
        current_file = filename
        while not exec_success and retry_count <= retry_limit:
            print(f"-------------retry----------{retry_count}---------------------------{current_file}")
            with open(current_file, 'r') as f:
                func0_code = f.read()

            errors_msg = error_msg_compile
            errors_msg1 = "."

            if "Assertion" in error_msg_compile:
                fixed_code = fix_with_llm_api_testcases(func0_code, errors_msg, errors_msg1, client, input_asm, ir_test, model_name=llm_model_name, timeout=llm_timeout)
            elif "PHI" in error_msg_compile:
                fixed_code = fix_with_llm_api_phi(func0_code, errors_msg, errors_msg1, client, input_asm, model_name=llm_model_name, timeout=llm_timeout)
            else:
                fixed_code = fix_with_llm_api(func0_code, errors_msg, errors_msg1, client, input_asm, model_name=llm_model_name, timeout=llm_timeout)

            retry_dir = os.path.join(output_ll_dir, f"retry_{retry_count}")
            os.makedirs(retry_dir, exist_ok=True)
            file_feedback = os.path.join(retry_dir, os.path.basename(filename))
            with open(file_feedback, "w") as f:
                f.write(fixed_code)
            current_file = file_feedback

            compile_success, exec_success, error_msg_compile, similarity = try_run_ll_file(current_file, ir_test, ir_func, temp_dir=temp_dir)
            retry_count += 1

        if compile_success:
            success_counter_compile[opt] += 1
        if exec_success:
            success_counter_exec[opt] += 1
        if similarity >= 0:
            edit_sim_dict[opt].append(similarity)
            edit_sim_all.append(similarity)

    print("\n=== Compile & Executable Summary ===")
    for opt in ["O0", "O1", "O2", "O3"]:
        compile_count = success_counter_compile[opt]
        exec_count = success_counter_exec[opt]
        sims = edit_sim_dict[opt]
        avg_sim = sum(sims) / len(sims) if sims else 0.0
        print(f"{opt}: Compile Success = {compile_count}, Executable Success = {exec_count}, Avg Similarity = {avg_sim:.4f}")

    total_compile = sum(success_counter_compile.values())
    total_exec = sum(success_counter_exec.values())
    avg_all = sum(edit_sim_all) / len(edit_sim_all) if edit_sim_all else 0.0
    print(f"\nTotal: Compile Success = {total_compile}, Executable Success = {total_exec}, Avg Similarity = {avg_all:.4f}")